name: scanwedge
description: A Flutter plugin to be able to work with the Zebra Datawedge
version: 0.0.1
homepage: https://github.com/Rokke/scanwedge

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: no.talgoe.scanwedge.scanwedge
        pluginClass: ScanwedgePlugin